# Generated by Django 4.1.3 on 2022-11-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsFeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeedmodel',
            name='message',
        ),
    ]
