# Generated by Django 4.1.3 on 2022-11-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsFeed', '0005_newsfeedimagesmodel_newsfeedmessagemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeedimagesmodel',
            name='images',
            field=models.FileField(blank=True, upload_to='newsFeed/'),
        ),
    ]
